#docker-compose.yml
services:
    php:
        build: ./docker/php
        volumes:
            - ./app:/var/www/symfony
        depends_on:
            - mysql
        networks:
            - mytheresaApiDemo

    nginx:
        build: ./docker/nginx
        ports:
            - "8081:80"
        volumes:
            - ./app:/var/www/symfony
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - mytheresaApiDemo

    mysql:
        image: mysql:8.0.33
        container_name: demo_mysql
        environment:
            MYSQL_ROOT_PASSWORD: s3cr3tR00t
            MYSQL_DATABASE: catalog
            MYSQL_USER: demo
            MYSQL_PASSWORD: demo
        ports:
            - 3306:3306
        expose:
            - 3306
        command:
            --default-authentication-plugin=mysql_native_password
            --performance_schema=OFF
            --character-set-server=utf8mb4
            --collation-server=utf8mb4_general_ci
            --explicit_defaults_for_timestamp=true
        volumes:
            - ./docker/db:/docker-entrypoint-initdb.d:ro
        networks:
            - mytheresaApiDemo

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            PMA_HOST: demo_mysql
            PMA_PORT: 3306
        ports:
            - 8080:80
        links:
            - mysql
        networks:
            - mytheresaApiDemo

networks:
    mytheresaApiDemo: