# Expose your documentation as JSON swagger compliant
app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

#app_health:
#    path: /api/health
#    methods: [GET]
#    defaults: { _controller: App\Controller\HealthCheck\HealthController::getStatus}

app_products:
    path: /api/products
    methods: [GET]
    defaults: { _controller: App\Controller\Products\ProductsController::getProducts}
