# Expose your documentation as JSON swagger compliant
app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

app_products:
    path: /products
    methods: [GET]
    defaults: { _controller: App\Controller\Products\ProductsController::getProducts}
